# version: '3'

services: 

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - go-network

  app:
    build: 
      context: go-app
    container_name: go-app
    environment:
      APIKEY: "${APIKEY}"
      USERNAME: "${USERNAME}"
      PASSWORD: "${PASSWORD}"
      MONGODB_URL: mongodb://mongodb:27017/sprout-dtr
    networks: 
      - go-network
    depends_on:
      - mongodb

  nginx:
    build: 
      context: nginx
    container_name: nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d/
    networks: 
      - go-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks: 
  go-network:
    driver: bridge
